export const environment = {
  production: true,
  REST_API_SERVER :'http://vps722937.ovh.net:8000/',
  RECENTMOVIES:'recentmovies',
  GENRES:'genres',
  SEARCHMOVIES:'search',
  DETAILSMOVIE:'detailsmovies',
  REGISTER:'register',
  LOGIN:'login_check',
  REFRESH_TOKEN:'token/refresh',
  USERNAME:'username',
  CRITICS:'critics',
  DOCRITIC:'docritic',
  ALLUSER:'admin/allusers',
  GETROLES:'admin/getroles',
  DELETEUSER:'admin/deleteuser',
};
