export const environment = {
  production: true,
  REST_API_SERVER :'http://vps722937.ovh.net:8000/',
  RECENTMOVIES:'recentmovies',
  GENRES:'genres',
  SEARCHMOVIES:'search',
  DETAILSMOVIE:'detailsmovies',
  REGISTER:'register',
  LOGIN:'login_check',
  REFRESH_TOKEN:'token/refresh',
  USERNAME:'username',
  CRITICS:'critics',
  DOCRITIC:'docritic',
  ALLUSER:'admin/allusers',
  GETROLES:'admin/getroles',
  DELETEUSER:'admin/deleteuser',
  ALLGENRES:'admin/allgenres',
  CREATEGENRE:'admin/creategenre',
  DELETEGENRE:'admin/deletegenre',
  UPDATEGENRE:'admin/updategenre',
  ALLCRITICS:'admin/allcritics',
  AUTOCOMPLETEMOVIE:'autocompletemovie',
  DELETECRITIC:'admin/deletecritic',
};
